cache:
    - C:\strawberry
install:
    - if not exist "C:\strawberry" cinst strawberryperl
    - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
build_script:
    -  C:\projects\%APPVEYOR_PROJECT_NAME%\idp-sealer-rollover -h

